name: Update Existing Tags

on:
    push:
        branches:
            - main
        files-ignore:
            - CHANGELOG

jobs:
    load-versions:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Execute Script
              run: ./scripts/update-existing-tags
